name: CloudMart Deploy

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: Student-RG-1879876
  AZURE_REGION: canadaeast
  BACKEND_CONTAINER_GROUP: cloudmart-backend
  FRONTEND_CONTAINER_GROUP: cloudmart-frontend-${{ github.run_number }}
  DOCKER_BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/cloudmart-api
  DOCKER_FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/cloudmart-frontend

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # LOGIN TO DOCKER HUB
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # BACKEND: BUILD + PUSH
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./applications/backend
          file: ./applications/backend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_BACKEND_IMAGE }}:latest
            ${{ env.DOCKER_BACKEND_IMAGE }}:${{ github.sha }}

      # LOGIN TO AZURE
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # BACKEND: DEPLOY TO ACI
      - name: Deploy backend to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          name: ${{ env.BACKEND_CONTAINER_GROUP }}
          image: ${{ env.DOCKER_BACKEND_IMAGE }}:latest
          dns-name-label: cloudmart-backend-${{ github.run_number }}
          location: ${{ env.AZURE_REGION }}
          cpu: 1
          memory: 1.5
          ports: 80
          environment-variables: |
            COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }}
            COSMOS_KEY=${{ secrets.COSMOS_KEY }}

      # FRONTEND: BUILD + PUSH
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./applications/frontend
          file: ./applications/frontend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_FRONTEND_IMAGE }}:latest
            ${{ env.DOCKER_FRONTEND_IMAGE }}:${{ github.sha }}

      # FRONTEND: DEPLOY TO ACI
      - name: Deploy frontend to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          name: ${{ env.FRONTEND_CONTAINER_GROUP }}
          image: ${{ env.DOCKER_FRONTEND_IMAGE }}:latest
          dns-name-label: cloudmart-frontend-${{ github.run_number }}
          location: ${{ env.AZURE_REGION }}
          cpu: 1
          memory: 1
          ports: 80
          ip-address: Public
          os-type: Linux
          protocol: TCP
          restart-policy: Always

