name: CloudMart Deploy

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: Student-RG-1879876
  AZURE_REGION: canadaeast
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/cloudmart-api

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -----------------------
      # BACKEND DEPLOYMENT
      # -----------------------
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./applications/backend
          file: ./applications/backend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          name: cloudmart-backend
          image: ${{ env.DOCKER_IMAGE_NAME }}:latest
          dns-name-label: cloudmart
          location: ${{ env.AZURE_REGION }}
          cpu: 1
          memory: 1.5
          ports: 80
          environment-variables: |
            COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }}
            COSMOS_KEY=${{ secrets.COSMOS_KEY }}

      # -----------------------
      # FRONTEND DEPLOYMENT
      # -----------------------
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./applications/frontend
          file: ./applications/frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cloudmart-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cloudmart-frontend:${{ github.sha }}

      - name: Deploy frontend to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          name: cloudmart-frontend
          image: ${{ secrets.DOCKERHUB_USERNAME }}/cloudmart-frontend:latest
          dns-name-label: cloudmart-ui-${{ github.run_number }}
          location: ${{ env.AZURE_REGION }}
          cpu: 1
          memory: 1
          ports: 80

